version: '3.9'

services:
  auth:
    build:
       context: .
       target: auth-app
    network_mode: host
    
    depends_on:
      - mongodb
  payment:
    build:
       context: .
       target: payment-service
    network_mode: host
    depends_on:
      - auth

  order:
    build:
       context: .
       target: order-app
    network_mode: host
    depends_on:
      - mongodb
      - auth
      - payment
  resturant:
    build:
       context: .
       target: resturant-app
    network_mode: host
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
        - internal_network
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - internal_network
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - "6440:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge
volumes:
  dbdata6: